### ISSUE TITLE
nixosModules: include port numbers for EL and CL

### ISSUE THREAD

**Issue by jhvst** [ponkila/homestaking-infra#36]
Currently, when I run

`nix eval --json github:ponkila/homestaking-infra#nixosConfigurations.dinar-ephemeral-alpha.config.lighthouse`

I get: 

`{"datadir":"/mnt/eth/lighthouse","enable":true,"endpoint":"192.168.100.31","exec":{"endpoint":"http://192.168.100.31:8551"},"mev-boost":{"endpoint":"http://192.168.100.31:18550"},"slasher":{"enable":false,"history-length":256,"max-db-size":16}}`

However, to combine this into a query command like so:

`curl -X GET "http://192.168.100.31:5052/eth/v1/beacon/headers/head" -H  "accept: application/json"`

I need to make it dynamic, e.g., like this:

`curl -X GET "http://$(nix eval --raw github:ponkila/homestaking-infra#nixosConfigurations.dinar-ephemeral-alpha.config.lighthouse.endpoint)/eth/v1/beacon/headers/head" -H  "accept: application/json"`

However, from the JSON returned, no port is included, which is required for the `curl` command to work. We should add port numbers into the `nixosModule` declaration to make a command composition like this work.

**Comment by tupakkatapa** [comment]
Solved by this commit [e9c2462](https://github.com/ponkila/homestaking-infra/pull/39/commits/e9c24623827ea7b624b1b6ef7695f3e16b11c354) in this pull request #39. Closing after merge.

Took also the prefix into account, so currently this:
`nix eval --json github:ponkila/homestaking-infra/feat/tweaks#nixosConfigurations.dinar-ephemeral-alpha.config.lighthouse.endpoint`

will return the whole address, like this:
`http://192.168.100.31:5052`
